/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmonitor;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author John Venice Almazan
 */
public class AdminUI extends javax.swing.JFrame {

    Connection myconObj = null;
    Statement mystatObj = null;
    ResultSet myresObj = null;

    /**
     * Creates new form TeacherUI
     *
     * @param uname
     */
    public AdminUI(String uname) {
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        setfullscreen();
        lblUname.setText(uname);
        lblUname.setVisible(false);
        lblName.setVisible(false);
        showTime();
        showgreet();
        selectall();
    }

    private void setfullscreen() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }

    private void showTime() {
        String url = "jdbc:derby://localhost:1527/SchoolMonitor";
        String user = "root";
        String pass = "password";
        String bar = lblUname.getText();

        try {
            myconObj = DriverManager.getConnection(url, user, pass);
            mystatObj = myconObj.createStatement();
            myresObj = mystatObj.executeQuery("SELECT * FROM ROOT.LOGIN WHERE USERNAME ='" + bar + "'");
            while (myresObj.next()) {
                String prefix = myresObj.getString("PREFIX");
                String Lastname = myresObj.getString("LASTNAME");
                String Name = prefix + " " + Lastname;
                lblName.setText(Name);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showgreet() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm aa");
        SimpleDateFormat t = new SimpleDateFormat("aa");
        if ("AM".equals(t.format(d))) {
            lblGreet.setText("Good Morning, " + lblName.getText());
        } else {
            lblGreet.setText("Good Afternoon, " + lblName.getText());
        }
    }

    public void selectall() {
        String url = "jdbc:derby://localhost:1527/SchoolMonitor";
        String user = "root";
        String pass = "password";
        try {
            myconObj = DriverManager.getConnection(url, user, pass);
            mystatObj = myconObj.createStatement();
            myresObj = mystatObj.executeQuery("SELECT BARCODE, FIRSTNAME, LASTNAME FROM ROOT.LOGIN WHERE CREDENTIAL = 'Teacher' AND GENDER = 'Male' AND DELETED = false");
            MaleTable.setModel(DbUtils.resultSetToTableModel(myresObj));

            myresObj = mystatObj.executeQuery("SELECT BARCODE, FIRSTNAME, LASTNAME FROM ROOT.LOGIN WHERE CREDENTIAL = 'Teacher' AND GENDER = 'Female' AND DELETED = false");
            FemaleTable.setModel(DbUtils.resultSetToTableModel(myresObj));

        } catch (SQLException e) {
            String print = e.toString();
            JOptionPane.showMessageDialog(null, print);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MaleTable = new javax.swing.JTable();
        lblGreet = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FemaleTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnViewTeacher = new javax.swing.JButton();
        btnEditMale = new javax.swing.JButton();
        btnAddTc = new javax.swing.JButton();
        btnDeleteMale = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblUname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnViewTeacher1 = new javax.swing.JButton();
        btnEditFemale = new javax.swing.JButton();
        BtnDeleteFemale = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 696));

        MaleTable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Barcode", "Firstname", "Lastname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MaleTable.setFocusable(false);
        MaleTable.setRowHeight(30);
        jScrollPane1.setViewportView(MaleTable);

        lblGreet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblGreet.setText("Good Morning, Mr. Almazan");

        FemaleTable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        FemaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Barcode", "Firstname", "Lastname"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        FemaleTable.setRowHeight(30);
        jScrollPane3.setViewportView(FemaleTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Male Teachers");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Female Teachers");

        btnViewTeacher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewTeacher.setText("View Female Info");
        btnViewTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewTeacherMouseClicked(evt);
            }
        });
        btnViewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTeacherActionPerformed(evt);
            }
        });

        btnEditMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditMale.setText("Edit Male Info");
        btnEditMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMaleMouseClicked(evt);
            }
        });

        btnAddTc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddTc.setText("Add Teacher");
        btnAddTc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTcMouseClicked(evt);
            }
        });

        btnDeleteMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteMale.setText("Removed Male Teacher");
        btnDeleteMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMaleMouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Change Password");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        lblUname.setText("username");

        lblName.setText("Name");

        btnViewTeacher1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewTeacher1.setText("View Male Info");
        btnViewTeacher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewTeacher1MouseClicked(evt);
            }
        });
        btnViewTeacher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTeacher1ActionPerformed(evt);
            }
        });

        btnEditFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditFemale.setText("Edit Female Info");
        btnEditFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditFemaleMouseClicked(evt);
            }
        });

        BtnDeleteFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnDeleteFemale.setText("Removed FemaleTeacher");
        BtnDeleteFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDeleteFemaleMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Log out");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblGreet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel1)))
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(517, 517, 517)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(36, 36, 36)
                                .addComponent(jButton2)
                                .addGap(432, 432, 432)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUname)
                                .addGap(84, 84, 84)
                                .addComponent(lblName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddTc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnDeleteFemale, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(61, 61, 61)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblGreet)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewTeacher1)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewTeacher)
                        .addGap(50, 50, 50)
                        .addComponent(btnAddTc)
                        .addGap(40, 40, 40)
                        .addComponent(btnEditMale)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditFemale)
                        .addGap(40, 40, 40)
                        .addComponent(btnDeleteMale)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDeleteFemale)
                        .addGap(40, 40, 40)
                        .addComponent(jButton5)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUname)
                            .addComponent(lblName))))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewTeacherActionPerformed

    private void btnViewTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTeacherMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex1 = FemaleTable.getSelectedRow();
        String Bar1 = FemaleTable.getValueAt(SelectedRowIndex1, 0).toString();
        ViewTeacher vs1 = new ViewTeacher(Bar1);
        vs1.show();
    }//GEN-LAST:event_btnViewTeacherMouseClicked

    private void btnViewTeacher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTeacher1MouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = MaleTable.getSelectedRow();
        String Bar = MaleTable.getValueAt(SelectedRowIndex, 0).toString();
        ViewTeacher vs = new ViewTeacher(Bar);
        vs.show();

    }//GEN-LAST:event_btnViewTeacher1MouseClicked

    private void btnViewTeacher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTeacher1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewTeacher1ActionPerformed

    private void btnAddTcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTcMouseClicked
        // TODO add your handling code here:
        RegisterTeacher regtc = new RegisterTeacher();
        regtc.show();
    }//GEN-LAST:event_btnAddTcMouseClicked

    private void btnEditMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMaleMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = MaleTable.getSelectedRow();
        String Bar = MaleTable.getValueAt(SelectedRowIndex, 0).toString();
        EditTeacher et = new EditTeacher(Bar);
        et.show();
    }//GEN-LAST:event_btnEditMaleMouseClicked

    private void btnEditFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFemaleMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex1 = FemaleTable.getSelectedRow();
        String Bar = FemaleTable.getValueAt(SelectedRowIndex1, 0).toString();
        EditTeacher et1 = new EditTeacher(Bar);
        et1.show();
        
    }//GEN-LAST:event_btnEditFemaleMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        selectall();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnDeleteMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMaleMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = MaleTable.getSelectedRow();
        String Bar = MaleTable.getValueAt(SelectedRowIndex, 0).toString();
        int p = JOptionPane.showConfirmDialog(null, "Is this really a deleted Teacher? This action cannot be undone", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Boolean yes = true;
                String sql = "update ROOT.LOGIN set DELETED = " + yes + " WHERE BARCODE = '" + Bar + "'";
           
                Statement update = myconObj.createStatement();
                update.executeUpdate(sql);
            }catch (Exception e){
                String print = e.toString();
                JOptionPane.showMessageDialog(null, print);
            }
            JOptionPane.showMessageDialog(null, "Deleted Successfully!", "Delete Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteMaleMouseClicked

    private void BtnDeleteFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeleteFemaleMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = FemaleTable.getSelectedRow();
        String Bar = FemaleTable.getValueAt(SelectedRowIndex, 0).toString();
        int p = JOptionPane.showConfirmDialog(null, "Is this really a deleted Teacher? This action cannot be undone", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Boolean yes = true;
                String sql = "update ROOT.LOGIN set DELETED = " + yes + " WHERE BARCODE = '" + Bar + "'";
           
                Statement update = myconObj.createStatement();
                update.executeUpdate(sql);
            }catch (Exception e){
                String print = e.toString();
                JOptionPane.showMessageDialog(null, print);
            }
            JOptionPane.showMessageDialog(null, "Deleted Successfully!", "Delete Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnDeleteFemaleMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        ChangePassword CP = new ChangePassword(lblUname.getText());
        CP.show();
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to Log-out your account?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            MainMonitor mm = new MainMonitor("CheckIn");
            mm.show();
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteFemale;
    private javax.swing.JTable FemaleTable;
    private javax.swing.JTable MaleTable;
    private javax.swing.JButton btnAddTc;
    private javax.swing.JButton btnDeleteMale;
    private javax.swing.JButton btnEditFemale;
    private javax.swing.JButton btnEditMale;
    private javax.swing.JButton btnViewTeacher;
    private javax.swing.JButton btnViewTeacher1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUname;
    // End of variables declaration//GEN-END:variables
}
