/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmonitor;

import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author John Venice Almazan
 */
public class SuperAdminUI extends javax.swing.JFrame {

    Connection myconObj = null;
    Statement mystatObj = null;
    ResultSet myresObj = null;

    /**
     * Creates new form TeacherUI
     *
     * @param uname
     */
    public SuperAdminUI(String uname) {
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        setfullscreen();
        lblUname.setText(uname);
        lblUname.setVisible(false);
        lblName.setVisible(false);
        showTime();
        showgreet();
        selectall();
    }

    private void setfullscreen() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }

    private void showTime() {
        String url = "jdbc:derby://localhost:1527/SchoolMonitor";
        String user = "root";
        String pass = "password";
        String bar = lblUname.getText();

        try {
            myconObj = DriverManager.getConnection(url, user, pass);
            mystatObj = myconObj.createStatement();
            myresObj = mystatObj.executeQuery("SELECT * FROM ROOT.ADMIN WHERE USERNAME ='" + bar + "'");
            while (myresObj.next()) {
                String Lastname = myresObj.getString("LASTNAME");
                String Name = Lastname;
                lblName.setText(Name);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showgreet() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm aa");
        SimpleDateFormat t = new SimpleDateFormat("aa");
        if ("AM".equals(t.format(d))) {
            lblGreet.setText("Good Morning, " + lblName.getText());
        } else {
            lblGreet.setText("Good Afternoon, " + lblName.getText());
        }
    }

    public void selectall() {
        String url = "jdbc:derby://localhost:1527/SchoolMonitor";
        String user = "root";
        String pass = "password";
        try {
            myconObj = DriverManager.getConnection(url, user, pass);
            mystatObj = myconObj.createStatement();
            myresObj = mystatObj.executeQuery("SELECT BARCODE, FIRSTNAME, LASTNAME, CREDENTIAL FROM ROOT.LOGIN WHERE CREDENTIAL != 'Teacher'");
            MaleTable.setModel(DbUtils.resultSetToTableModel(myresObj));

        } catch (SQLException e) {
            String print = e.toString();
            JOptionPane.showMessageDialog(null, print);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MaleTable = new javax.swing.JTable();
        lblGreet = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUname = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        btnViewInfo = new javax.swing.JButton();
        btnAddTc = new javax.swing.JButton();
        btnEditMale = new javax.swing.JButton();
        btnDeleteMale = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 696));

        MaleTable.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        MaleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Barcode", "Firstname", "Lastname", "Credential"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MaleTable.setFocusable(false);
        MaleTable.setRowHeight(30);
        jScrollPane1.setViewportView(MaleTable);

        lblGreet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblGreet.setText("Good Morning, Mr. Almazan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ADMIN/STAFF/VISITORS");

        lblUname.setText("Username");

        lblName.setText("Name");

        btnViewInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewInfo.setText("View Info");
        btnViewInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewInfoMouseClicked(evt);
            }
        });
        btnViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInfoActionPerformed(evt);
            }
        });

        btnAddTc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddTc.setText("Add Admin/Staff/Visitor");
        btnAddTc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTcMouseClicked(evt);
            }
        });

        btnEditMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditMale.setText("Edit Info");
        btnEditMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMaleMouseClicked(evt);
            }
        });

        btnDeleteMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteMale.setText("Removed Admin/Staff");
        btnDeleteMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMaleMouseClicked(evt);
            }
        });
        btnDeleteMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMaleActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Log out");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteMale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddTc, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(btnEditMale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblGreet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblUname)
                        .addGap(152, 152, 152)
                        .addComponent(lblName)))
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblGreet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnAddTc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnEditMale, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnDeleteMale, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUname)
                            .addComponent(lblName)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewInfoMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = MaleTable.getSelectedRow();
        String Bar = MaleTable.getValueAt(SelectedRowIndex, 0).toString();
        ViewInfo vi = new ViewInfo(Bar);
        vi.show();
    }//GEN-LAST:event_btnViewInfoMouseClicked

    private void btnViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewInfoActionPerformed

    private void btnAddTcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTcMouseClicked
        // TODO add your handling code here:
        RegisterAdmin regad = new RegisterAdmin();
        regad.show();
    }//GEN-LAST:event_btnAddTcMouseClicked

    private void btnEditMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMaleMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = MaleTable.getSelectedRow();
        String Bar = MaleTable.getValueAt(SelectedRowIndex, 0).toString();
        EditInfo et = new EditInfo(Bar);
        et.show();
    }//GEN-LAST:event_btnEditMaleMouseClicked

    private void btnDeleteMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMaleMouseClicked
        // TODO add your handling code here:
        int SelectedRowIndex = MaleTable.getSelectedRow();
        String Bar = MaleTable.getValueAt(SelectedRowIndex, 0).toString();
        int p = JOptionPane.showConfirmDialog(null, "Is this really a deleted admin/staff? This action cannot be undone", "Delete Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                Boolean yes = true;
                String sql = "update ROOT.LOGIN set DELETED = " + yes + " WHERE BARCODE = '" + Bar + "'";

                Statement update = myconObj.createStatement();
                update.executeUpdate(sql);
            }catch (Exception e){
                String print = e.toString();
                JOptionPane.showMessageDialog(null, print);
            }
            JOptionPane.showMessageDialog(null, "Deleted Successfully!", "Delete Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteMaleMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        selectall();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to Log-out your account?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            MainMonitor mm = new MainMonitor("CheckIn");
            mm.show();
            this.dispose();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnDeleteMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MaleTable;
    private javax.swing.JButton btnAddTc;
    private javax.swing.JButton btnDeleteMale;
    private javax.swing.JButton btnEditMale;
    private javax.swing.JButton btnViewInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUname;
    // End of variables declaration//GEN-END:variables
}
